<img src="https://i.ibb.co/93sNcdhp/Logo-pmat-color.png" align="right" width="150">

<br>

# **Intervalos de confianza para la Proporción**

## **Objetivos de aprendizaje**

- Comprender el concepto de **proporción poblacional** y su estimación a partir de una muestra.
- Calcular **intervalos de confianza (IC)** para una proporción con el enfoque normal aproximado.
- Interpretar el nivel de confianza y el margen de error en contextos reales.
- Analizar cómo influyen el tamaño de muestra y el nivel de confianza en la precisión de la estimación.

In [ ]:
# @title
%%html
<div style="border: 4px solid #006d77; border-radius: 0px; overflow: hidden; font-family: sans-serif; max-width: 800px; margin-bottom: 20px;">

  <div style="background-color: #000000; color: #ffc107; padding: 10px 15px; font-weight: bold; font-size: 16px; display: flex; align-items: center;">
    <span style="margin-right: 10px; font-size: 18px;">💡</span>
    <span>Intervalos de confianza para la media y la proporción</span>
  </div>

  <div style="background-color: #ffffff; padding: 20px; display: flex; align-items: center; justify-content: space-between;">

    <div style="color: #000000; flex: 1; padding-right: 30px; font-size: 14px; line-height: 1.5;">
      ¿Sabes cuándo estimar un promedio y cuándo una tasa de éxito?
      <b>Escanea o haz clic sobre el código QR</b> para aprender a diferenciar y construir intervalos de confianza,
      ya sea para la media de una variable o la proporción de una categoría.
      </div>

    <div style="flex-shrink: 0;">
      <a href="https://duoc.h5p.com/content/1292748480894628278" target="_blank">
        <img src="https://i.ibb.co/hJf9LxSs/IC-media-y-p.png"
             alt="QR Code"
             style="width: 100px; height: 100px; border: none;">
      </a>
    </div>

  </div>

  <div style="background-color: #000000; color: #ffc107; padding: 8px 15px; font-weight: bold; font-size: 16px;">
    Presentación interactiva H5P
  </div>

</div>


## **Recordatorio clave**

- **Estimador de la proporción:**$\hspace{0.5 cm}$  $\hat{p} = \frac{x}{n}$,
  donde $x$ es el número de éxitos y $n$ el tamaño de la muestra.

- **Error estándar:** $\hspace{0.5 cm}$ $SE = \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}$

- **Intervalo de confianza para la proporción:** $\hspace{0.5 cm}$ $IC = \hat{p} \pm z_{\alpha/2} \cdot SE$

<br>
<br>

### **Comprobando condiciones antes de calcular IC**

Antes de aplicar las fórmulas anteriores, verifica estas 2 condiciones obligatorias en tus datos:

1.  **¿La muestra es aleatoria?**
    * Debe ser representativa del contexto del problema.
2.  **¿Hay suficientes éxitos y fracasos?** (Condición de Normalidad)
    * Calcula $n \cdot \hat{p}$ (debe ser $\geq 5$)
    * Calcula $n \cdot (1-\hat{p})$ (debe ser $\geq 5$)

*Si ambas respuestas son "SÍ", puedes proceder con el cálculo.*

# **Actividad 1 — Servidores estables en un centro de datos**

En un centro de datos que soporta múltiples aplicaciones críticas, la estabilidad de los servidores es esencial para garantizar disponibilidad y continuidad de servicio. Durante una semana de monitoreo se revisaron 200 servidores, registrando si experimentaron reinicios inesperados que podrían implicar caídas momentáneas o pérdida de datos. En total, se detectaron 26 servidores con incidentes de inestabilidad. El equipo de infraestructura necesita estimar cuál es la proporción real de servidores que podrían presentar este tipo de problemas para priorizar acciones de mantenimiento preventivo y asignar recursos de forma eficiente.

1. Calcula la proporción muestral $\hat{p}$ de servidores inestables.

In [ ]:
PMuestral = 26/200
print(PMuestral)

0.13


13% de los servidores mostraron inestabilidad

2. ¿Es posible comprobar que es posible utilizar una aproximación normal?

In [ ]:
Condicion1 = 200*PMuestral
Condicion2 = 200*(1-PMuestral)
print(Condicion1)
print(Condicion2)

26.0
174.0


Se cumplen ambas condiciones para utilizar un intervalo usando una aproximación normal, ya que se cumple que ambos resultados son mayor o igual que 10.

2. Construye un IC al 95% para la proporción poblacional.  


In [ ]:
import numpy as np
import pandas as pd
import scipy.stats as st

n = 200
num_exitos = 26
#si en enunciado dan cantidad de exitos
#num_exitos = valor del enunciado

#si hay que calcular la cantidad de exitos
#exitos=muestra[muestra == valor de exito]
#num_exitos=len(exitos)

PMuestral = num_exitos/n
alpha = 0.05 #95% confianza
z = st.norm.ppf(1-alpha/2) #valor crítico
se = np.sqrt(PMuestral*(1-PMuestral)/n) #error estandar
ic = (PMuestral - z*se, PMuestral + z*se)
print(f"IC al 95%: {(ic[0]*100):.2f}% a {(ic[1]*100):.2f}%")

IC al 95%: 8.34% a 17.66%


3. Interpreta el resultado para el equipo técnico.

Con un 95% de confianza, el porcentaje de inestabilidad de los servidores es de un 8.34% a un 17.66%

# **Actividad 2 — Tasa de aprobación de un examen en educación**

En una asignatura clave de una carrera en educación superior, aprobar los exámenes iniciales es fundamental para medir el aprendizaje y orientar apoyos tempranos. En la primera evaluación participaron 120 estudiantes, de los cuales 72 aprobaron. El equipo docente quiere estimar la proporción real de estudiantes que aprueban este tipo de evaluaciones para tomar decisiones sobre reforzamientos y ajustar la planificación de la asignatura.

1. Calcula $ \hat{p}$ y construye un intervalo de confianza del 95% para la proporción poblacional. Imprime los resultados en representación decimal y porcentual.

In [ ]:
PMuestral_examen = 72/120
print(PMuestral_examen)
print()

Condicion1 = 120*PMuestral_examen
Condicion2 = 120*(1-PMuestral_examen)
print(Condicion1)
print(Condicion2)
print()

import numpy as np
import pandas as pd
import scipy.stats as st

n = 120
num_exitos = 72
#si en enunciado dan cantidad de exitos
#num_exitos = valor del enunciado

#si hay que calcular la cantidad de exitos
#exitos=muestra[muestra == valor de exito]
#num_exitos=len(exitos)

PMuestral_examen = num_exitos/n
alpha = 0.05 #95% confianza
z = st.norm.ppf(1-alpha/2) #valor crítico
se = np.sqrt(PMuestral_examen*(1-PMuestral_examen)/n) #error estandar
ic = (PMuestral_examen - z*se, PMuestral_examen + z*se)
print(f"IC al 95%: {(ic[0]*100):.2f}% a {(ic[1]*100):.2f}%")

0.6

72.0
48.0

IC al 95%: 51.23% a 68.77%


2. Interpreta para el equipo docente: ¿cuál es el rango de aprobación estimado en todo el grupo de estudiantes?

Con un 95% de confianza, el rango de aprobación estimado en el grupo estudiantil es de un 51.23% a un 68.77%

# **Actividad 3 — Satisfacción de clientes en compras online**

Una empresa de comercio electrónico está evaluando la calidad de su servicio al cliente. Para esto revisó 500 compras recientes, preguntando a los compradores si el servicio recibido fue “satisfactorio”. Entre ellos, 420 clientes respondieron afirmativamente. La empresa busca estimar, con un 90% de confianza, la proporción real de clientes satisfechos y comprender cómo cambiaría la precisión de la estimación si se aumentara el nivel de confianza a 99%.

1. ¿Cuál es el valor de la proporción muestral $ \hat{p}$?

In [ ]:
PMuestal_clientes = 420/500
print(PMuestal_clientes)

0.84


Un 84% de los clientes respondieron afirmativamente

2. Estima e interpreta el intervalo de confianza al 90% para la proporción poblacional de clientes satisfechos.

In [ ]:
Condicion1 = 500*PMuestal_clientes
Condicion2 = 500*(1-PMuestal_clientes)
print(Condicion1)
print(Condicion2)
print()

import numpy as np
import pandas as pd
import scipy.stats as st

n = 500
num_exitos = 420
#si en enunciado dan cantidad de exitos
#num_exitos = valor del enunciado

#si hay que calcular la cantidad de exitos
#exitos=muestra[muestra == valor de exito]
#num_exitos=len(exitos)

PMuestral_clientes = num_exitos/n
alpha = 0.1 #90% confianza
z = st.norm.ppf(1-alpha/2) #valor crítico
se = np.sqrt(PMuestral_clientes*(1-PMuestral_clientes)/n) #error estandar
ic = (PMuestral_clientes - z*se, PMuestral_clientes + z*se)
print(f"IC al 90%: {(ic[0]*100):.2f}% a {(ic[1]*100):.2f}%")

420.0
80.00000000000001

IC al 90%: 81.30% a 86.70%


Con un 90% de confianza, la proporción de clientes satisfechos es de un 81.3% a un 86.7%

3. ¿Cómo cambia el tamaño del intervalo y la precisión de la estimación al aumentar el nivel de confianza del 90% al 99%?

In [ ]:
Condicion1 = 500*PMuestal_clientes
Condicion2 = 500*(1-PMuestal_clientes)
print(Condicion1)
print(Condicion2)
print()

import numpy as np
import pandas as pd
import scipy.stats as st

n = 500
num_exitos = 420
#si en enunciado dan cantidad de exitos
#num_exitos = valor del enunciado

#si hay que calcular la cantidad de exitos
#exitos=muestra[muestra == valor de exito]
#num_exitos=len(exitos)

PMuestral_clientes = num_exitos/n
alpha = 0.01 #90% confianza
z = st.norm.ppf(1-alpha/2) #valor crítico
se = np.sqrt(PMuestral_clientes*(1-PMuestral_clientes)/n) #error estandar
ic = (PMuestral_clientes - z*se, PMuestral_clientes + z*se)
print(f"IC al 99%: {(ic[0]*100):.2f}% a {(ic[1]*100):.2f}%")

420.0
80.00000000000001

IC al 99%: 79.78% a 88.22%


Al cambiar el IC al 99%, aumenta el rango de

## **Gráfico interactivo**

Utiliza el siguiente gráfico interactivo para explorar cómo cambia el intervalo de confianza al modificar el nivel de confianza, el tamaño muestral ($n$) y el valor de $x$.

Al mover los deslizadores, observa especialmente:
* Cómo varía el ancho del intervalo al cambiar el nivel de confianza,
* Qué ocurre con la precisión de la estimación.

*Indicación: Ejecuta la celda de código para visualizar el gráfico interactivo*


In [ ]:
# @title
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt
from ipywidgets import interact,  IntSlider, Dropdown, fixed

def viz_ic_proporcion_curva(x, n, confianza=0.95, titulo=None):
    # Evitar casos inválidos
    if x < 0 or x > n:
        return

    phat = x / n
    z = st.norm.ppf(1 - (1-confianza)/2)
    se = np.sqrt(phat*(1 - phat)/n)
    L, U = phat - z*se, phat + z*se

    # Rango para la curva normal aproximada
    xs = np.linspace(max(0, phat - 4*se), min(1, phat + 4*se), 800)
    ys = st.norm.pdf((xs - phat)/se) / se

    # Gráfico
    plt.figure(figsize=(7,4))
    plt.plot(xs, ys)

    # sombreado del intervalo de confianza
    mask = (xs >= L) & (xs <= U)
    plt.fill_between(xs, ys, where=mask, alpha=0.3)
    plt.axvline(phat, linestyle="--", linewidth=1)
    plt.axvline(L, linestyle="--", linewidth=1)
    plt.axvline(U, linestyle="--", linewidth=1)

    if titulo is None:
        titulo = f"IC {int(confianza*100)}% para p con aproximación normal"
    plt.title(titulo)
    plt.xlabel("Proporción")
    plt.ylabel("Densidad (aprox. normal)")
    plt.text(phat, max(ys)*0.9, f"$\\hat p$={phat:.3f}", ha="center")
    plt.text(L, max(ys)*0.6, f"L={L:.4f}", ha="center", rotation=90, va="center")
    plt.text(U, max(ys)*0.6, f"U={U:.4f}", ha="center", rotation=90, va="center")
    plt.tight_layout()
    plt.show()

# --- INTERACTIVIDAD (único agregado real) ---
interact(
    viz_ic_proporcion_curva,
    x=IntSlider(value=70, min=0, max=500, step=10, description='x'),
    n=IntSlider(value=200, min=20, max=500, step=10, description='n'),
    confianza=Dropdown(options=[0.90, 0.95, 0.99], value=0.90, description='Confianza'),
    titulo=fixed(None)
);


interactive(children=(IntSlider(value=70, description='x', max=500, step=10), IntSlider(value=200, description…

4. ¿Qué representa el nivel de confianza en un IC y cómo se interpreta en el contexto de este problema?

El nivel de confianza representa el grado de seguridad asociado al método utilizado para construir el intervalo de confianza.

En este problema, decir que el intervalo tiene un nivel de confianza del 90% o del 99% significa que, si se repitiera el procedimiento muchas veces con distintas muestras del mismo tamaño, aproximadamente el 90% o el 99% de los intervalos construidos contendrían la verdadera proporción poblacional.


# **Actividad 4 — Eficacia de un tratamiento en salud**

En un estudio piloto, se evaluó la eficacia de un tratamiento en un grupo de pacientes que presentan la misma condición médica.

La información recolectada se encuentra en la base de datos que puedes descargar **[aquí](https://docs.google.com/spreadsheets/d/14jQZkHA1M8iD4-q5KHAL5qydOEso7tCN/export?format=xlsx)**, la cual contiene el registro de cada paciente y si presentó o no mejoría tras el tratamiento.

En la variable mejora, el valor 1 indica que el paciente presentó mejoría, mientras que el valor 0 indica que no presentó mejoría.

Utiliza esta información para estimar la proporción poblacional de pacientes que presentan mejoría y analizar la incertidumbre asociada a dicha estimación.


1. Carga la base de datos y determina el tamaño de la muestra ($n$) y el número de pacientes que presentaron mejoría ($x$).

In [7]:
import numpy as np
import pandas as pd

muestra = pd.read_excel('G3_A4_tratamiento_salud.xlsx')

n = len(muestra)
x = df['mejora'].sum()
print(n)
print(x)

50
34


34 pacientes demostraron mejorías, 50 es la cantidad total de pacientes

2. Calcula la proporción muestral $\hat{p}$ y construye un intervalo de confianza del 99 % para la proporción poblacional de pacientes que presentan mejoría.

In [13]:
PMuestral_mejora = x/n
print(PMuestral_mejora)

#Condicion para usar normal
n = len(muestra)
PMuestral_mejora = 34/n

cond_1 = n*PMuestral_mejora
cond_2 = n*(1-PMuestral_mejora)

print(f'{cond_1},{cond_2:.2f}') #ambas debes ser >=10

0.68
34.0,16.00


In [16]:
import numpy as np
import pandas as pd
import scipy.stats as st

n = len(muestra)
#si en enunciado dan cantidad de exitos
#num_exitos = valor del enunciado

#si hay que calcular la cantidad de exitos
#exitos=muestra[muestra == valor de exito]
#num_exitos=len(exitos)

PMuestral_mejora = 34/50
alpha = 0.01 #99% confianza
z = st.norm.ppf(1-alpha/2) #valor crítico
se = np.sqrt(PMuestral_mejora*(1-PMuestral_mejora)/n) #error estandar
ic = (PMuestral_mejora - z*se, PMuestral_mejora + z*se)
print(f"IC al 99%: {(ic[0]*100):.2f}% a {(ic[1]*100):.2f}%")

IC al 99%: 51.01% a 84.99%


3. Interpreta los resultados obtenidos como si debieras reportarlo en un informe médico, explicando qué indica el rango estimado y cuán precisa es esta estimación.

Con un 99% de confianza, la proporción de pacientes que presentan mejorías, es de un 51.01% a un 84.99%

# **Actividad 5 — Análisis de opiniones en redes sociales**

Un equipo de analítica digital monitorea la percepción de un nuevo producto tecnológico a través de redes sociales. Para evaluar el impacto de la campaña de lanzamiento, se recopilaron tuits relacionados con el producto, identificando si el tono de cada mensaje es positivo o negativo.

El área de marketing se ha fijado como meta alcanzar al menos un 70% de opiniones positivas y quiere saber si los datos disponibles respaldan ese objetivo con un nivel de confianza del 95%.

Descarga la base de datos **[aquí](https://docs.google.com/spreadsheets/d/1kRZe090udX45FpcUwJYCHvebpBJu0X9q/export?format=xlsx)** y considera que, en la variable “es_positivo”, el valor 1 indica una opinión positiva y el valor 0 una opinión negativa.


1. Carga la base y determina el tamaño de la muestra ($n$) y la cantidad de opiniones positivas ($x$).

In [26]:
import numpy as np
import pandas as pd

muestra_redes = pd.read_excel('G3_A5_opiniones_redes_sociales.xlsx')
muestra_redes.head()

n = len(muestra)
x = muestra_redes['es_positivo'].sum()
print(n)
print(x)

2000
1420


2000 es la cantidad total de tuits, mientras que la cantidad de opiniones positivas son 1420 tuits

2. Calcula $\hat{p}$ y construye un IC del 95% de confianza para la proporción poblacional de opiniones positivas.

In [27]:
PMuestral_redes = x/n
print(PMuestral_redes)

#Condicion para usar normal
n = len(muestra)
PMuestral_mejora = 1420/2000

cond_1 = n*PMuestral_redes
cond_2 = n*(1-PMuestral_redes)

print(f'{cond_1},{cond_2:.2f}') #ambas debes ser >=10

0.71
1420.0,580.00


In [28]:
import numpy as np
import pandas as pd
import scipy.stats as st

#si en enunciado dan cantidad de exitos
#num_exitos = valor del enunciado

#si hay que calcular la cantidad de exitos
#exitos=muestra[muestra == valor de exito]
#num_exitos=len(exitos)

alpha = 0.05 #95% confianza
z = st.norm.ppf(1-alpha/2) #valor crítico
se = np.sqrt(PMuestral_redes*(1-PMuestral_redes)/n) #error estandar
ic = (PMuestral_redes - z*se, PMuestral_redes + z*se)
print(f"IC al 95%: {(ic[0]*100):.2f}% a {(ic[1]*100):.2f}%")

IC al 95%: 69.01% a 72.99%


3. Concluye si, con 95% de confianza, el equipo de marketing ha alcanzado su meta.

Con un 95% de confianza, el equipo de marketing ha alcanzado su meta, ya que la proporción alcanzada va desde un 69.01% hasta un 72.99%, por lo tanto superaron la meta del 70% establecida para opiniones positivas

# **Actividad 6 - Proporción de actitud positiva**

Se aplica un cuestionario que mide la actitud hacia la autoevaluación de la calidad educativa a una muestra aleatoria de alumnos de la Facultad de Ciencias Matemáticas. De un total de 364 alumnos, 247 evidencian actitud positiva hacia la autoevaluación.

Se solicita que estime la proporción de alumnos de esta Facultad con actitud positiva hacia la autoevaluación de la calidad educativa con un nivel de confianza del 90%.

In [39]:
import numpy as np
import pandas as pd
import scipy.stats as st

n = 364
x = 247

#Condicion para usar normal
p_muestral = x/n

cond_1 = n*p_muestral
cond_2 = n*(1-p_muestral)

print(f'{cond_1},{cond_2:.2f}') #ambas debes ser >=10

247.0,117.00


In [41]:
#si en enunciado dan cantidad de exitos
#num_exitos = valor del enunciado

#si hay que calcular la cantidad de exitos
#exitos=muestra[muestra == valor de exito]
#num_exitos=len(exitos)

alpha = 0.1 #90% confianza
z = st.norm.ppf(1-alpha/2) #valor crítico
se = np.sqrt(p_muestral*(1-p_muestral)/n) #error estandar
ic = (p_muestral - z*se, p_muestral + z*se)
print(f"IC al 90%: {(ic[0]*100):.2f}% a {(ic[1]*100):.2f}%")

IC al 90%: 63.83% a 71.88%


Con un 90% de confianza, la proporción de alumnos con actitud positiva, varía desde un 63.83% hasta un 71.88%

# **Actividad 7 - Control de calidad con intervalos**

La Comisión de Salud pretende implantar un programa de ayuda a familias con familiares dependientes. El programa es financiado por un organismo público y ejecutado por los municipios.

Por errores inevitables, no todas las familias a las que se subvenciona cumplen los requisitos exigidos, pero el organismo supervisor del programa considera aceptable que esto ocurra en no más del 4% de los casos. Si se supera este porcentaje, el municipio será sancionado.

En un municipio se muestrean 200 familias y se detecta que 12 de ellas no cumplen las condiciones exigidas. Considerando un nivel de confianza del 90%, ¿debe sancionarse al municipio?


In [42]:
import numpy as np
import pandas as pd
import scipy.stats as st

n = 200
x = 12

#Condicion
p_muestral = x/n

cond_1 = n*p_muestral
cond_2 = n*(1-p_muestral)

print(f'{cond_1},{cond_2:.2f}') #ambas debes ser >=10

12.0,188.00


In [43]:
alpha = 0.1 #90% confianza
z = st.norm.ppf(1-alpha/2) #valor crítico
se = np.sqrt(p_muestral*(1-p_muestral)/n) #error estandar
ic = (p_muestral - z*se, p_muestral + z*se)
print(f"IC al 90%: {(ic[0]*100):.2f}% a {(ic[1]*100):.2f}%")

IC al 90%: 3.24% a 8.76%


Con un 90% de confianza, este rango supera el 4%, llegando a 8.76%, por lo que el municipio debe ser sancionado.

# **Actividad de cierre — Aplicación a tu contexto**

Imagina un escenario real de tu área profesional en el que necesites estimar una proporción relevante (ej.: porcentaje de clientes satisfechos, tasa de aprobación, proporción de fallas, etc.).

1.	Describe la proporción que deseas estimar y explica por qué sería útil conocerla en el contexto que imaginaste.

2.	Describe cómo obtendrías una muestra adecuada para estimar dicha proporción.
3.	Indica si se cumplirían las condiciones para utilizar la aproximación normal y justifica tu respuesta.

4.	Elige un nivel de confianza y explica tu decisión, considerando el equilibrio entre precisión de la estimación y nivel de seguridad.

5.	En el escenario que planteaste, reflexiona sobre cómo el tamaño de la muestra y el nivel de confianza influyen en la precisión del intervalo de confianza y en la toma de decisiones. ¿Qué podrías modificar para reducir el margen de error de tu estimación?


# **Con este laboratorio aprendiste a:**

*	Construir intervalos de confianza para proporciones y decidir cuándo la aproximación normal es válida.
*	Interpretar el efecto del tamaño muestral y del nivel de confianza sobre la precisión de la estimación.
*	Utilizar intervalos de confianza para respaldar decisiones basadas en metas o criterios de control.
*	Aplicar los conceptos de inferencia estadística a tu propio contexto profesional.
